FROM node:alpine as builder

WORKDIR /mnt

COPY . .

RUN npm i

RUN npm run build

RUN mv dist/bundle.js dist/bundle.cjs

FROM node:alpine

WORKDIR /mnt

COPY --from=builder /mnt/dist ./dist

COPY --from=builder /mnt/node_modules ./node_modules

COPY --from=builder /mnt/package.json .

COPY --from=builder /mnt/package-lock.json .


EXPOSE 8000

CMD ["node", "dist/bundle.cjs"]